import { Project, Beneficiary, Outcome } from '@/lib/types/data-fabric';

export const CANONICAL_PROJECTS: Project[] = [
  {
    id: 'PROJ-NDB-SOIL-01',
    code: 'NDB-SOIL-01',
    name: 'Nandurbar Rainfed Organic Cluster Infrastructure',
    schemeId: 'AGR-004',
    schemeCode: 'PKVY',
    districtId: 'DIST-27',
    districtLgdCode: '512',
    districtName: 'Nandurbar',
    budgetCr: 14.2,
    utilizedCr: 5.9,
    status: 'In-Progress',
    milestonesTotal: 24,
    milestonesCompleted: 10,
    completionRate: 41.6,
    coordinates: [21.37, 74.24],
    startDate: '2024-04-01',
    targetCompletionDate: '2026-03-31',
    verifiedOnGround: true,
  },
  {
    id: 'PROJ-GDC-HOUSING-02',
    code: 'GDC-HOUSE-02',
    name: 'Gadchiroli Forest Habitation Pucca Housing Block 4',
    schemeId: 'RUR-003',
    schemeCode: 'PMAY-G',
    districtId: 'DIST-34',
    districtLgdCode: '501',
    districtName: 'Gadchiroli',
    budgetCr: 18.5,
    utilizedCr: 9.1,
    status: 'Delayed',
    milestonesTotal: 30,
    milestonesCompleted: 14,
    completionRate: 46.7,
    coordinates: [20.18, 80.0],
    startDate: '2024-02-15',
    targetCompletionDate: '2025-12-31',
    verifiedOnGround: true,
  },
  {
    id: 'PROJ-WSM-TAP-03',
    code: 'WSM-TAP-03',
    name: 'Washim Jal Jeevan Gravity Pipeline & Overhead Reservoir',
    schemeId: 'JAL-001',
    schemeCode: 'JJM',
    districtId: 'DIST-16',
    districtLgdCode: '525',
    districtName: 'Washim',
    budgetCr: 16.4,
    utilizedCr: 7.5,
    status: 'Delayed',
    milestonesTotal: 22,
    milestonesCompleted: 10,
    completionRate: 45.4,
    coordinates: [20.11, 77.13],
    startDate: '2024-01-10',
    targetCompletionDate: '2026-06-30',
    verifiedOnGround: true,
  },
  {
    id: 'PROJ-PUN-HEALTH-04',
    code: 'PUN-HEALTH-04',
    name: 'Pune District Ayushman Bharat Cashless Empanelment Network',
    schemeId: 'HLT-001',
    schemeCode: 'AB-PMJAY',
    districtId: 'DIST-25',
    districtLgdCode: '516',
    districtName: 'Pune',
    budgetCr: 42.0,
    utilizedCr: 36.8,
    status: 'Completed',
    milestonesTotal: 50,
    milestonesCompleted: 48,
    completionRate: 96.0,
    coordinates: [18.52, 73.85],
    startDate: '2023-08-01',
    targetCompletionDate: '2025-08-01',
    verifiedOnGround: true,
  },
];

export const CANONICAL_BENEFICIARIES: Beneficiary[] = [
  {
    id: 'BEN-NDB-SMALLHOLDERS',
    category: 'Small & Marginal Tribal Farmers',
    schemeId: 'AGR-004',
    schemeCode: 'PKVY',
    districtId: 'DIST-27',
    districtName: 'Nandurbar',
    targetCount: 54000,
    verifiedCount: 22800,
    dbtStatus: 'Disbursed',
    aadhaarSeededRate: 72.4,
    coverageRate: 42.2,
    vulnerableSubgroups: ['Bhil Tribe', 'Pawra Tribe', 'Rainfed Cultivators'],
  },
  {
    id: 'BEN-GDC-FOREST-HH',
    category: 'Forest-Dwelling Houseless Families',
    schemeId: 'RUR-003',
    schemeCode: 'PMAY-G',
    districtId: 'DIST-34',
    districtName: 'Gadchiroli',
    targetCount: 42000,
    verifiedCount: 19800,
    dbtStatus: 'Pending',
    aadhaarSeededRate: 68.1,
    coverageRate: 47.1,
    vulnerableSubgroups: ['Madia Gond', 'Pardhan'],
  },
  {
    id: 'BEN-WSM-RURAL-HH',
    category: 'Rural Potable Water Deficit Households',
    schemeId: 'JAL-001',
    schemeCode: 'JJM',
    districtId: 'DIST-16',
    districtName: 'Washim',
    targetCount: 68000,
    verifiedCount: 31000,
    dbtStatus: 'Seeded',
    aadhaarSeededRate: 84.5,
    coverageRate: 45.6,
  },
];

export const CANONICAL_OUTCOMES: Outcome[] = [
  {
    id: 'OUT-SOIL-CARBON',
    metricName: 'Soil Organic Carbon Index (+0.2% Target)',
    description: 'Biological carbon density increase in certified rainfed farming plots.',
    baselineValue: 0.38,
    targetValue: 0.58,
    achievedValue: 0.44,
    unit: '% organic carbon',
    achievementRate: 30.0,
    status: 'Lagging',
    schemeId: 'AGR-004',
    districtId: 'DIST-27',
    lastMeasuredAt: '2026-09-15',
  },
  {
    id: 'OUT-WATER-TAP-ACCESS',
    metricName: 'Rural FHTC Potable Water Access Coverage',
    description: 'Percentage of rural households with certified potable continuous water connection.',
    baselineValue: 24.0,
    targetValue: 100.0,
    achievedValue: 46.0,
    unit: '% households',
    achievementRate: 46.0,
    status: 'Lagging',
    schemeId: 'JAL-001',
    districtId: 'DIST-16',
    lastMeasuredAt: '2026-09-30',
  },
  {
    id: 'OUT-PUCCA-HOUSING-RATIO',
    metricName: 'Disaster-Resilient Pucca Housing Completion Rate',
    description: 'Geo-tagged completed pucca residential units delivered with sanitation & electricity.',
    baselineValue: 18.0,
    targetValue: 100.0,
    achievedValue: 49.2,
    unit: '% target families',
    achievementRate: 49.2,
    status: 'Critical',
    schemeId: 'RUR-003',
    districtId: 'DIST-34',
    lastMeasuredAt: '2026-10-01',
  },
];
