import { Scheme } from '@/lib/types/data-fabric';

export interface CanonicalSchemeEntry extends Scheme {
  gazetteName: string;
  aliases: string[];
}

export const CANONICAL_SCHEMES_REGISTRY: CanonicalSchemeEntry[] = [
  {
    id: 'AGR-001',
    code: 'PM-KISAN',
    name: 'PM-KISAN (Direct Income Support)',
    officialName: 'Pradhan Mantri Kisan Samman Nidhi',
    gazetteName: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    ministryId: 'MIN-01',
    ministryName: 'Ministry of Agriculture and Farmers Welfare',
    department: 'Department of Agriculture & Farmers Welfare',
    sector: 'Income Support & Direct Benefit Transfer',
    targetGroup: 'Landholding Small & Marginal Farmers',
    startYear: 2019,
    status: 'Active',
    budgetAllocationCr: 60000,
    fundUtilizedCr: 48200,
    utilizationRate: 80,
    beneficiariesCount: 110000000,
    projectsCount: 36,
    coverageRate: 88,
    outcomeIndex: 86,
    summary:
      'Central sector income support scheme providing ₹6,000 per year in three equal installments directly to bank accounts of farmer families.',
    objectives: [
      'Supplement financial needs of landholding farmers for procuring inputs.',
      'Protect farmers from informal usurious moneylenders.',
      'Ensure 100% Aadhaar-seeded Direct Benefit Transfer.',
    ],
    keyDistricts: ['Nandurbar', 'Gadchiroli', 'Pune', 'Nashik', 'Solapur', 'Yavatmal'],
    aliases: [
      'PM Kisan',
      'PM-KISAN',
      'Pradhan Mantri Kisan Samman Nidhi',
      'PM Kisan Samman Nidhi Scheme',
      'PM Kisan Nidhi',
      'Kisan Samman Nidhi',
      'PM-Kisan DBT',
      'AGR-001',
    ],
  },
  {
    id: 'AGR-004',
    code: 'PKVY',
    name: 'PM Scheme A (Paramparagat Krishi Vikas Yojana)',
    officialName: 'Paramparagat Krishi Vikas Yojana (PKVY)',
    gazetteName: 'Paramparagat Krishi Vikas Yojana — Sub-Mission on Organic Farming',
    ministryId: 'MIN-01',
    ministryName: 'Ministry of Agriculture and Farmers Welfare',
    department: 'Department of Agriculture & Farmers Welfare',
    sector: 'Agriculture & Soil Health',
    targetGroup: 'Small & Marginal Organic Farmers',
    startYear: 2015,
    status: 'Review',
    budgetAllocationCr: 320,
    fundUtilizedCr: 249,
    utilizationRate: 78,
    beneficiariesCount: 1200000,
    projectsCount: 84,
    coverageRate: 71,
    outcomeIndex: 78,
    summary:
      'Centrally sponsored scheme promoting organic farming through cluster approach and participatory guarantee system certification.',
    objectives: [
      'Promote natural, chemical-free organic farming practices in tribal and rainfed zones.',
      'Establish certified farmer clusters with direct market linkage.',
      'Reduce production costs and enhance soil biological health.',
    ],
    keyDistricts: ['Nandurbar', 'Gadchiroli', 'Yavatmal', 'Washim'],
    aliases: [
      'PKVY',
      'PM Scheme A',
      'Paramparagat Krishi Vikas Yojana',
      'PKVY Soil Health',
      'Paramparagat Krishi',
      'Organic Cluster Farming Scheme',
      'AGR-004',
    ],
  },
  {
    id: 'AGR-008',
    code: 'MOVCDNER',
    name: 'PM Scheme B (Organic Value Chain Initiative)',
    officialName: 'Mission Organic Value Chain Development / Cluster Push',
    gazetteName: 'Mission Organic Value Chain Development for North Eastern & Rainfed Regions',
    ministryId: 'MIN-01',
    ministryName: 'Ministry of Agriculture and Farmers Welfare',
    department: 'Department of Agricultural Research and Education',
    sector: 'Agriculture & Value Chain',
    targetGroup: 'Organic Farmer Producer Organizations',
    startYear: 2017,
    status: 'Active',
    budgetAllocationCr: 285,
    fundUtilizedCr: 198,
    utilizationRate: 69,
    beneficiariesCount: 450000,
    projectsCount: 52,
    coverageRate: 64,
    outcomeIndex: 72,
    summary:
      'Value-chain centric intervention linking organic grower clusters with collection centres, post-harvest grading, and certified export corridors.',
    objectives: [
      'Build end-to-end organic value chain infrastructure.',
      'Empower Farmer Producer Companies with cold chain and pack houses.',
      'Facilitate international brand building and PGS-India certification.',
    ],
    keyDistricts: ['Nandurbar', 'Gadchiroli', 'Dhule', 'Gondia'],
    aliases: [
      'MOVCDNER',
      'MOVCD',
      'PM Scheme B',
      'Organic Value Chain Push',
      'Organic Value Chain Initiative',
      'Mission Organic Value Chain Development',
      'AGR-008',
    ],
  },
  {
    id: 'RUR-002',
    code: 'PMGSY',
    name: 'PMGSY (Rural Roads Connectivity)',
    officialName: 'Pradhan Mantri Gram Sadak Yojana',
    gazetteName: 'Pradhan Mantri Gram Sadak Yojana Phase-III',
    ministryId: 'MIN-02',
    ministryName: 'Ministry of Rural Development',
    department: 'Department of Rural Development',
    sector: 'Rural Infrastructure',
    targetGroup: 'Unconnected Rural Habitations',
    startYear: 2000,
    status: 'Active',
    budgetAllocationCr: 19000,
    fundUtilizedCr: 15400,
    utilizationRate: 81,
    beneficiariesCount: 42000000,
    projectsCount: 310,
    coverageRate: 84,
    outcomeIndex: 82,
    summary:
      'All-weather road connectivity mission connecting remote and tribal habitations to essential economic and healthcare hubs.',
    objectives: [
      'Provide single all-weather road connectivity to eligible unconnected habitations.',
      'Upgrade existing rural through routes and major rural links.',
      'Integrate GIS-based OMMS monitoring.',
    ],
    keyDistricts: ['Nandurbar', 'Gadchiroli', 'Dhule', 'Chandrapur'],
    aliases: [
      'PMGSY',
      'PMGSY Rural Roads',
      'Pradhan Mantri Gram Sadak Yojana',
      'Gram Sadak Yojana',
      'PM Gram Sadak',
      'RUR-002',
    ],
  },
  {
    id: 'RUR-003',
    code: 'PMAY-G',
    name: 'PMAY-G (Rural Housing)',
    officialName: 'Pradhan Mantri Awaas Yojana - Gramin',
    gazetteName: 'Pradhan Mantri Awaas Yojana (Gramin)',
    ministryId: 'MIN-02',
    ministryName: 'Ministry of Rural Development',
    department: 'Department of Rural Development',
    sector: 'Rural Housing',
    targetGroup: 'Houseless & Dilapidated House Families',
    startYear: 2016,
    status: 'Active',
    budgetAllocationCr: 54500,
    fundUtilizedCr: 41200,
    utilizationRate: 76,
    beneficiariesCount: 29500000,
    projectsCount: 1420,
    coverageRate: 79,
    outcomeIndex: 81,
    summary:
      'Provides financial assistance for construction of pucca houses with hygienic cooking space and basic amenities.',
    objectives: [
      'Deliver disaster-resilient housing to all socio-economically verified families.',
      'Convergence with Swachh Bharat and PM Ujjwala Yojana.',
      'Geo-tagged milestone verification before DBT fund tranche releases.',
    ],
    keyDistricts: ['Gadchiroli', 'Nandurbar', 'Chandrapur', 'Bhandara'],
    aliases: [
      'PMAY-G',
      'PMAYG',
      'PMAY Gramin',
      'Pradhan Mantri Awaas Yojana - Gramin',
      'PMAY-G Rural Housing',
      'Pradhan Mantri Awas Yojana Gramin',
      'Rural Housing Mission',
      'RUR-003',
    ],
  },
  {
    id: 'RUR-005',
    code: 'SHABARI-AWAS',
    name: 'State Shabari Tribal Housing Mission',
    officialName: 'Shabari Adivasi Gharkul Yojana',
    gazetteName: 'Shabari Adivasi Gharkul Yojana (Tribal Housing)',
    ministryId: 'MIN-02',
    ministryName: 'Ministry of Rural Development',
    department: 'Department of Rural Development',
    sector: 'Tribal Housing',
    targetGroup: 'Scheduled Tribe Forest Habitation Families',
    startYear: 2018,
    status: 'Active',
    budgetAllocationCr: 650,
    fundUtilizedCr: 410,
    utilizationRate: 63,
    beneficiariesCount: 140000,
    projectsCount: 48,
    coverageRate: 58,
    outcomeIndex: 69,
    summary:
      'State-sponsored housing scheme targeting Scheduled Tribe families living in temporary shelters in scheduled and tribal sub-plan areas.',
    objectives: [
      'Ensure 100% pucca housing for remote forest tribes.',
      'Direct top-up subsidy to supplement PMAY-G grants.',
    ],
    keyDistricts: ['Nandurbar', 'Gadchiroli', 'Palghar', 'Dhule'],
    aliases: [
      'Shabari Awas',
      'Shabari Gharkul',
      'State Shabari Tribal Housing Mission',
      'Shabari Adivasi Gharkul Yojana',
      'RUR-005',
    ],
  },
  {
    id: 'JAL-001',
    code: 'JJM',
    name: 'Jal Jeevan Mission (Har Ghar Jal)',
    officialName: 'Jal Jeevan Mission',
    gazetteName: 'Jal Jeevan Mission — National Rural Drinking Water Mission',
    ministryId: 'MIN-03',
    ministryName: 'Ministry of Jal Shakti',
    department: 'Department of Drinking Water and Sanitation',
    sector: 'Water Security & Sanitation',
    targetGroup: 'Rural Households & Village Schools',
    startYear: 2019,
    status: 'Accelerated',
    budgetAllocationCr: 70000,
    fundUtilizedCr: 51200,
    utilizationRate: 73,
    beneficiariesCount: 152000000,
    projectsCount: 2400,
    coverageRate: 78,
    outcomeIndex: 76,
    summary:
      'Universal potable piped water supply scheme providing 55 litres per capita per day to every rural household.',
    objectives: [
      'Provide functional household tap connection (FHTC) to every rural dwelling.',
      'Promote village water sanitation committees for long-term sustainability.',
      'Mandate water quality surveillance via sensor-based telemetry.',
    ],
    keyDistricts: ['Nandurbar', 'Washim', 'Jalna', 'Hingoli', 'Beed'],
    aliases: [
      'JJM',
      'Jal Jeevan Mission',
      'Har Ghar Jal',
      'JJM Har Ghar Jal',
      'National Rural Drinking Water Mission',
      'Jal Jeevan',
      'JAL-001',
    ],
  },
  {
    id: 'JAL-003',
    code: 'ATAL-BHUJAL',
    name: 'Atal Bhujal Yojana (Groundwater Management)',
    officialName: 'Atal Bhujal Yojana (ABHY)',
    gazetteName: 'Atal Bhujal Yojana — National Groundwater Management Scheme',
    ministryId: 'MIN-03',
    ministryName: 'Ministry of Jal Shakti',
    department: 'Department of Water Resources, River Development and Ganga Rejuvenation',
    sector: 'Groundwater Sustainability',
    targetGroup: 'Water-Stressed Village Gram Panchayats',
    startYear: 2020,
    status: 'Active',
    budgetAllocationCr: 6000,
    fundUtilizedCr: 3840,
    utilizationRate: 64,
    beneficiariesCount: 8500000,
    projectsCount: 180,
    coverageRate: 61,
    outcomeIndex: 70,
    summary:
      'Community-led sustainable groundwater management scheme in water-stressed districts.',
    objectives: [
      'Strengthen institutional framework for participatory groundwater management.',
      'Incentivize gram panchayats to adopt water budgeting and water security plans.',
    ],
    keyDistricts: ['Washim', 'Jalna', 'Solapur', 'Ahmednagar'],
    aliases: [
      'Atal Bhujal',
      'Atal Bhujal Yojana',
      'ABHY',
      'Groundwater Management Scheme',
      'JAL-003',
    ],
  },
  {
    id: 'HLT-001',
    code: 'AB-PMJAY',
    name: 'Ayushman Bharat PM-JAY',
    officialName: 'Ayushman Bharat Pradhan Mantri Jan Arogya Yojana',
    gazetteName: 'Ayushman Bharat National Health Protection Mission',
    ministryId: 'MIN-04',
    ministryName: 'Ministry of Health and Family Welfare',
    department: 'Department of Health & Family Welfare',
    sector: 'Universal Health Protection',
    targetGroup: 'Bottom 40% Vulnerable Families',
    startYear: 2018,
    status: 'Active',
    budgetAllocationCr: 7500,
    fundUtilizedCr: 6100,
    utilizationRate: 81,
    beneficiariesCount: 55000000,
    projectsCount: 820,
    coverageRate: 85,
    outcomeIndex: 87,
    summary:
      'World largest government funded healthcare assurance scheme offering ₹5 Lakh per family per year for secondary and tertiary hospitalization.',
    objectives: [
      'Mitigate catastrophic out-of-pocket medical expenditure.',
      'Empower poorest households with cashless hospital admission.',
      'Standardize clinical treatment package rates across state borders.',
    ],
    keyDistricts: ['Mumbai City', 'Pune', 'Nagpur', 'Chhatrapati Sambhajinagar', 'Nandurbar'],
    aliases: [
      'AB-PMJAY',
      'PM-JAY',
      'PMJAY',
      'Ayushman Bharat',
      'Ayushman Bharat PM-JAY',
      'Pradhan Mantri Jan Arogya Yojana',
      'National Health Protection Scheme',
      'HLT-001',
    ],
  },
  {
    id: 'SBM-001',
    code: 'SBM-G',
    name: 'Swachh Bharat Mission - Gramin',
    officialName: 'Swachh Bharat Mission (Gramin)',
    gazetteName: 'Swachh Bharat Mission Phase-II (ODF Plus)',
    ministryId: 'MIN-03',
    ministryName: 'Ministry of Jal Shakti',
    department: 'Department of Drinking Water and Sanitation',
    sector: 'Rural Sanitation & Solid/Liquid Waste',
    targetGroup: 'Rural Communities & Gram Panchayats',
    startYear: 2014,
    status: 'Active',
    budgetAllocationCr: 7192,
    fundUtilizedCr: 5900,
    utilizationRate: 82,
    beneficiariesCount: 115000000,
    projectsCount: 1100,
    coverageRate: 91,
    outcomeIndex: 89,
    summary:
      'Sustaining Open Defecation Free (ODF) status and providing solid and liquid waste management infrastructure across rural India.',
    objectives: [
      'Ensure ODF sustainability across all villages.',
      'Implement village greywater and plastic waste management systems.',
    ],
    keyDistricts: ['Nandurbar', 'Gadchiroli', 'Pune', 'Kolhapur'],
    aliases: [
      'SBM-G',
      'SBMG',
      'Swachh Bharat Gramin',
      'Swachh Bharat Mission - Gramin',
      'ODF Plus Mission',
      'SBM-001',
    ],
  },
];

export class SchemeRegistry {
  private static codeMap = new Map<string, CanonicalSchemeEntry>(
    CANONICAL_SCHEMES_REGISTRY.map((s) => [s.code.toUpperCase(), s])
  );
  private static idMap = new Map<string, CanonicalSchemeEntry>(
    CANONICAL_SCHEMES_REGISTRY.map((s) => [s.id.toUpperCase(), s])
  );
  private static nameMap = new Map<string, CanonicalSchemeEntry>(
    CANONICAL_SCHEMES_REGISTRY.map((s) => [s.officialName.toLowerCase(), s])
  );

  static getSchemeByCode(code: string): CanonicalSchemeEntry | undefined {
    return this.codeMap.get(code.toUpperCase().trim());
  }

  static getSchemeById(id: string): CanonicalSchemeEntry | undefined {
    return this.idMap.get(id.toUpperCase().trim());
  }

  static getSchemeByName(name: string): CanonicalSchemeEntry | undefined {
    return this.nameMap.get(name.toLowerCase().trim());
  }

  static getAllSchemes(): CanonicalSchemeEntry[] {
    return CANONICAL_SCHEMES_REGISTRY;
  }
}
